[package]
name                   = "nh-remote"
version                = "0.1.0"
publish                = false
edition.workspace      = true
license.workspace      = true
rust-version.workspace = true

[lints]
workspace = true


[lib]
path = "src/remote.rs"

[dependencies]
anstyle.workspace             = true
clap.workspace                = true
clap-verbosity-flag.workspace = true
color-eyre.workspace          = true
dix.workspace                 = true
inquire.workspace             = true
nh-command.workspace          = true
nh-installable.workspace      = true
nh-passthrough.workspace      = true
nh-util.workspace             = true
nix.workspace                 = true
proptest.workspace            = true
regex.workspace               = true
secrecy.workspace             = true
semver.workspace              = true
serde_json.workspace          = true
serial_test.workspace         = true
shlex.workspace               = true
signal-hook.workspace         = true
subprocess.workspace          = true
tempfile.workspace            = true
thiserror.workspace           = true
tracing.workspace             = true
which.workspace               = true
yansi.workspace               = true
