[package]
name                   = "nh-installable"
version                = "0.1.0"
publish                = false
edition.workspace      = true
license.workspace      = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
path = "src/installable.rs"

[dependencies]
clap.workspace        = true
color-eyre.workspace  = true
serial_test.workspace = true
tracing.workspace     = true
yansi.workspace       = true
